package com.deguan.xuelema.androidapp.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEACHER_ENTITY".
 */
public class TeacherEntity {

    private String user_id;
    private String username;
    private String nickname;
    private String gender;
    private String education;
    private String user_headimg;
    private String date_joined;
    private String speciality;
    private String speciality_name;
    private String fee;
    private String years;
    private String apply_job;
    private String demand_fee;
    private String service_type;
    private String service_type_txt;
    private String grade_type_txt;
    private String is_passed;
    private String haoping_num;
    private String order_rank;
    private String distance;
    private String status1;
    private String status2;
    private String signature;

    public TeacherEntity() {
    }

    public TeacherEntity(String user_id, String username, String nickname, String gender, String education, String user_headimg, String date_joined, String speciality, String speciality_name, String fee, String years, String apply_job, String demand_fee, String service_type, String service_type_txt, String grade_type_txt, String is_passed, String haoping_num, String order_rank, String distance, String status1, String status2, String signature) {
        this.user_id = user_id;
        this.username = username;
        this.nickname = nickname;
        this.gender = gender;
        this.education = education;
        this.user_headimg = user_headimg;
        this.date_joined = date_joined;
        this.speciality = speciality;
        this.speciality_name = speciality_name;
        this.fee = fee;
        this.years = years;
        this.apply_job = apply_job;
        this.demand_fee = demand_fee;
        this.service_type = service_type;
        this.service_type_txt = service_type_txt;
        this.grade_type_txt = grade_type_txt;
        this.is_passed = is_passed;
        this.haoping_num = haoping_num;
        this.order_rank = order_rank;
        this.distance = distance;
        this.status1 = status1;
        this.status2 = status2;
        this.signature = signature;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getUser_headimg() {
        return user_headimg;
    }

    public void setUser_headimg(String user_headimg) {
        this.user_headimg = user_headimg;
    }

    public String getDate_joined() {
        return date_joined;
    }

    public void setDate_joined(String date_joined) {
        this.date_joined = date_joined;
    }

    public String getSpeciality() {
        return speciality;
    }

    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    public String getSpeciality_name() {
        return speciality_name;
    }

    public void setSpeciality_name(String speciality_name) {
        this.speciality_name = speciality_name;
    }

    public String getFee() {
        return fee;
    }

    public void setFee(String fee) {
        this.fee = fee;
    }

    public String getYears() {
        return years;
    }

    public void setYears(String years) {
        this.years = years;
    }

    public String getApply_job() {
        return apply_job;
    }

    public void setApply_job(String apply_job) {
        this.apply_job = apply_job;
    }

    public String getDemand_fee() {
        return demand_fee;
    }

    public void setDemand_fee(String demand_fee) {
        this.demand_fee = demand_fee;
    }

    public String getService_type() {
        return service_type;
    }

    public void setService_type(String service_type) {
        this.service_type = service_type;
    }

    public String getService_type_txt() {
        return service_type_txt;
    }

    public void setService_type_txt(String service_type_txt) {
        this.service_type_txt = service_type_txt;
    }

    public String getGrade_type_txt() {
        return grade_type_txt;
    }

    public void setGrade_type_txt(String grade_type_txt) {
        this.grade_type_txt = grade_type_txt;
    }

    public String getIs_passed() {
        return is_passed;
    }

    public void setIs_passed(String is_passed) {
        this.is_passed = is_passed;
    }

    public String getHaoping_num() {
        return haoping_num;
    }

    public void setHaoping_num(String haoping_num) {
        this.haoping_num = haoping_num;
    }

    public String getOrder_rank() {
        return order_rank;
    }

    public void setOrder_rank(String order_rank) {
        this.order_rank = order_rank;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getStatus1() {
        return status1;
    }

    public void setStatus1(String status1) {
        this.status1 = status1;
    }

    public String getStatus2() {
        return status2;
    }

    public void setStatus2(String status2) {
        this.status2 = status2;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

}
