package com.deguan.xuelema.androidapp.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XUQIU_ENTITY".
 */
public class XuqiuEntity {

    private String publisher_id;
    private String publisher_name;
    private String publisher_headimg;
    private String publisher_gender;
    private String id;
    private String content;
    private String service_type;

    public String getService_type() {
        return service_type;
    }

    public void setService_type(String service_type) {
        this.service_type = service_type;
    }

    private String service_type_txt;
    private String grade_id;
    private String grade_name;
    private String course_id;
    private String course_name;
    private String education_id;
    private String education_name;
    private String fee;
    private String duration;
    private String gender;
    private String age;
    private String created;
    private String lng;
    private String lat;
    private String distance;
    private String status;

    public XuqiuEntity() {
    }

    public XuqiuEntity(String publisher_id, String publisher_name, String publisher_headimg, String publisher_gender, String id, String content, String service_type_txt, String grade_id, String grade_name, String course_id, String course_name, String education_id, String education_name, String fee, String duration, String gender, String age, String created, String lng, String lat, String distance, String status) {
        this.publisher_id = publisher_id;
        this.publisher_name = publisher_name;
        this.publisher_headimg = publisher_headimg;
        this.publisher_gender = publisher_gender;
        this.id = id;
        this.content = content;
        this.service_type_txt = service_type_txt;
        this.grade_id = grade_id;
        this.grade_name = grade_name;
        this.course_id = course_id;
        this.course_name = course_name;
        this.education_id = education_id;
        this.education_name = education_name;
        this.fee = fee;
        this.duration = duration;
        this.gender = gender;
        this.age = age;
        this.created = created;
        this.lng = lng;
        this.lat = lat;
        this.distance = distance;
        this.status = status;
    }

    public String getPublisher_id() {
        return publisher_id;
    }

    public void setPublisher_id(String publisher_id) {
        this.publisher_id = publisher_id;
    }

    public String getPublisher_name() {
        return publisher_name;
    }

    public void setPublisher_name(String publisher_name) {
        this.publisher_name = publisher_name;
    }

    public String getPublisher_headimg() {
        return publisher_headimg;
    }

    public void setPublisher_headimg(String publisher_headimg) {
        this.publisher_headimg = publisher_headimg;
    }

    public String getPublisher_gender() {
        return publisher_gender;
    }

    public void setPublisher_gender(String publisher_gender) {
        this.publisher_gender = publisher_gender;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getService_type_txt() {
        return service_type_txt;
    }

    public void setService_type_txt(String service_type_txt) {
        this.service_type_txt = service_type_txt;
    }

    public String getGrade_id() {
        return grade_id;
    }

    public void setGrade_id(String grade_id) {
        this.grade_id = grade_id;
    }

    public String getGrade_name() {
        return grade_name;
    }

    public void setGrade_name(String grade_name) {
        this.grade_name = grade_name;
    }

    public String getCourse_id() {
        return course_id;
    }

    public void setCourse_id(String course_id) {
        this.course_id = course_id;
    }

    public String getCourse_name() {
        return course_name;
    }

    public void setCourse_name(String course_name) {
        this.course_name = course_name;
    }

    public String getEducation_id() {
        return education_id;
    }

    public void setEducation_id(String education_id) {
        this.education_id = education_id;
    }

    public String getEducation_name() {
        return education_name;
    }

    public void setEducation_name(String education_name) {
        this.education_name = education_name;
    }

    public String getFee() {
        return fee;
    }

    public void setFee(String fee) {
        this.fee = fee;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getCreated() {
        return created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
