package com.deguan.xuelema.androidapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.deguan.xuelema.androidapp.entities.XuqiuEntity;
import com.deguan.xuelema.androidapp.entities.TeacherEntity;

import com.deguan.xuelema.androidapp.dao.XuqiuEntityDao;
import com.deguan.xuelema.androidapp.dao.TeacherEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig xuqiuEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;

    private final XuqiuEntityDao xuqiuEntityDao;
    private final TeacherEntityDao teacherEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        xuqiuEntityDaoConfig = daoConfigMap.get(XuqiuEntityDao.class).clone();
        xuqiuEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        xuqiuEntityDao = new XuqiuEntityDao(xuqiuEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);

        registerDao(XuqiuEntity.class, xuqiuEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
    }
    
    public void clear() {
        xuqiuEntityDaoConfig.getIdentityScope().clear();
        teacherEntityDaoConfig.getIdentityScope().clear();
    }

    public XuqiuEntityDao getXuqiuEntityDao() {
        return xuqiuEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

}
